// hello-world-vue/src/components/CurrentTime.vue
<template>
  <h3 class="text-xl font-normal">Current Time: {{ time.toLocaleTimeString() }}</h3>
</template>

<script>
export default {
  name: "CurrentTime",
  data: () => ({
    intervalId: null,
    time: new Date(),
  }),
  mounted() {
    this.intervalId = setInterval(() => this.time = new Date(), 1000);
    console.log(`Started intervalId ${this.intervalId}`);
  },
  beforeDestroy() {
    console.log(`Clearing intervalId ${this.intervalId}`);
    clearInterval(this.intervalId);
  }
}
</script>

<style scoped>

</style>

// hello-world-react/src/CurrentTime.js
import { useState, useEffect } from 'react';

const CurrentTime = () => {
    const [time, setTime] = useState(new Date());

    useEffect(() => {
       const intervalId = setInterval(() => setTime(new Date()), 1000);
       console.log(`Started timer ${intervalId}`);
       return () => {
           console.log(`Clearing timer ${intervalId}`);
           clearInterval(intervalId);
       }
    }, []);

    return <h3 className="text-xl font-normal">Current Time: {time.toLocaleTimeString()}</h3>
};

export default CurrentTime;
