// hello-world-svelte/src/routes/dialogs.svelte
<script context="module">
    export const prerender = true;
    import NavButton from '$lib/NavButton.svelte';
    import SuccessDialog from '$lib/SuccessDialog.svelte';
</script>

<script>
    let showDialog = false;
</script>

<div>
    <nav>
        <NavButton clickHandler={() => showDialog = !showDialog}>{showDialog ? 'Hide' : 'Show'} Dialog</NavButton>
    </nav>
    <SuccessDialog open={showDialog} closeHandler={() => showDialog = false}/>
</div>

// hello-world-react/src/routes/Dialogs.js
import { useState } from "react";
import NavButton from "../NavButton";
import SuccessDialog from "../SuccessDialog";

const Dialogs = () => {
    const [showDialog, setShowDialog] = useState(false);
    return (
        <>
            <nav>
                <NavButton onClick={() => setShowDialog(!showDialog)}>{showDialog ? 'Hide' : 'Show'} Dialog</NavButton>
            </nav>
            <SuccessDialog open={showDialog} onClose={() => setShowDialog(false)}/>
        </>
    )
};

export default Dialogs;
