// hello-world-react/src/routes/Jokes.js
import { useState } from "react";
import Joke from "../Joke";
import NavButton from "../NavButton";
import Section from "../Section";

const Jokes = () => {
    const [showJoke, setShowJoke] = useState(true);

    return (
        <>
            <nav>
                <NavButton onClick={() => setShowJoke(!showJoke)}>{showJoke ? 'Hide' : 'Show'} Joke</NavButton>
            </nav>
            <Section show={showJoke}>
                <Joke/>
            </Section>
        </>
    )
};

export default Jokes;

// hello-world-svelte/src/routes/jokes.svelte
<script context="module">
    export const prerender = true;
    import Joke from '$lib/Joke.svelte';
    import NavButton from '$lib/NavButton.svelte';
    import Tile from '$lib/Tile.svelte';
</script>

<script>
    let showJoke = true;
</script>

<div>
    <nav>
        <NavButton clickHandler={() => showJoke = !showJoke}>{showJoke ? 'Hide' : 'Show'} Joke</NavButton>
    </nav>
    <Tile show={showJoke}>
        <Joke/>
    </Tile>
</div>
