// hello-world-react/src/routes/Simple.js
import { useState } from "react";
import Counter from "../Counter";
import CurrentTime from "../CurrentTime";
import NavButton from "../NavButton";
import Section from "../Section";

const Simple = () => {
    const [showCounter, setShowCounter] = useState(true);
    const [showTime, setShowTime] = useState(true);

    return (
        <>
            <nav>
                <NavButton onClick={() => setShowCounter(!showCounter)}>{showCounter ? 'Hide' : 'Show'} Counter</NavButton>
                <NavButton onClick={() => setShowTime(!showTime)}>{showTime ? 'Hide' : 'Show'} Time</NavButton>
            </nav>
            <Section show={showCounter}>
                <Counter initialCount={5}/>
            </Section>
            <Section show={showTime}>
                <CurrentTime/>
            </Section>
        </>
    )
};

export default Simple;

// hello-world-svelte/src/routes/simple.svelte
<script context="module">
    export const prerender = true;
    import Counter from '$lib/Counter.svelte';
    import CurrentTime from '$lib/CurrentTime.svelte';
    import NavButton from '$lib/NavButton.svelte';
    import Tile from '$lib/Tile.svelte';
</script>

<script>
    let showCounter = true;
    let showTimer = true;
</script>

<div>
    <nav>
        <NavButton clickHandler={() => showCounter = !showCounter}>{showCounter ? 'Hide' : 'Show'} Counter</NavButton>
        <NavButton clickHandler={() => showTimer = !showTimer}>{showTimer ? 'Hide' : 'Show'} Timer</NavButton>
    </nav>
    <Tile show={showCounter}>
        <Counter initialCount="5" />
    </Tile>
    <Tile show={showTimer}>
        <CurrentTime />
    </Tile>
</div>
