// hello-world-svelte/src/lib/Button.svelte
<script>
    export let type = 'button';
    export let disabled = false;
    export let clickHandler;
</script>

<button {type}
        {disabled}
        class={`inline-block mx-1 border py-0 px-3 rounded-md border-black text-white bg-black ${disabled ? 'cursor-not-allowed opacity-40' : 'hover:text-black hover:bg-white'}`}
        on:click={clickHandler}>
    <slot></slot>
</button>

// hello-world-vue/src/components/Button.vue
<template>
  <button :type="type"
          @click.stop="onClick"
          :disabled="disabled"
          :class="[ disabled ? 'cursor-not-allowed opacity-40' : 'hover:text-black hover:bg-white' ]"
          class="inline-block mx-1 border py-0 px-3 rounded-md border-black text-white bg-black">
    <slot>Button</slot>
  </button>
</template>

<script>
export default {
  name: "Button",
  props: {
    type: {
      type: String,
      default: 'button',
    },
    onClick: {
      type: Function,
      default: () => {},
    },
    disabled: Boolean,
  },
}
</script>

<style scoped>

</style>
